#region Copyright (c) 2000-2024 Developer Express Inc.
/*
{*******************************************************************}
{                                                                   }
{       Developer Express .NET Component Library                    }
{                                                                   }
{                                                                   }
{       Copyright (c) 2000-2024 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   ARE CONFIDENTIAL AND PROPRIETARY TRADE                          }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET    }
{   CONTROLS AS PART OF AN EXECUTABLE PROGRAM ONLY.                 }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}
*/
#endregion Copyright (c) 2000-2024 Developer Express Inc.

using DevExpress.Mvvm;
using DevExpress.Mvvm.Native;
using DevExpress.Xpf.DemoBase;
using DevExpress.Xpf.DemoBase.Helpers;
using DevExpress.Xpf.DemoBase.Helpers.TextColorizer;
using System;
using System.Diagnostics;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
namespace DevExpress.Xpf.DemoBase {
	[NoAutogeneratedCodeFiles]
	public abstract partial class ShowcaseBrowserModule : DemoModule {
		public ShowcaseBrowserModule() {
			IShowcaseInfo[] showcases = CreateShowcases();
			Content = new ShowcaseBrowserModuleCore(showcases);
		}
		public ShowcaseBrowserModuleCore Core { get { return Content as ShowcaseBrowserModuleCore; } }
		protected abstract IShowcaseInfo[] CreateShowcases();
		protected static ShowcaseInfo LoadShowcase(string name, string helpUri, string path, Type[] types = null, bool showCodeBehind = false, SourceCodeOrder codeOrder = SourceCodeOrder.CodeBehindFirst, bool useNewDocsSite = false) {
			return ShowcaseBrowserModuleCore.LoadShowcase(name, helpUri, path, types, showCodeBehind, codeOrder, useNewDocsSite);
		}
		public override void ProcessArguments(string[] arguments) {
			Core.Do(x => x.ProcessArguments(arguments));
		}
		public override string GetArgument() {
			return Core == null ? string.Empty : Core.GetArgument();
		}
	}
}
